lab_1/urls.py
from django.urls import re_path
from .views import *
#url for app

app_name = "lab_1"
urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^home/$', home, name='home'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^family/$', family, name='family'),
    re_path(r'^form/$', form, name='form'),
    re_path(r'^formz/$', form_sched, name='formz'),
    re_path(r'^formz/submit/$', create_sched, name='submit'),
    re_path(r'^formz/delete/$', delete_all, name='delete'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from django.contrib.auth import views
from lab_1.views import index as index_lab1


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls', namespace='lab_1')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^lab-8/', include('story_8.urls')),
    re_path(r'^lab-9/', include('story_9.urls')),
    re_path(r'^lab-10/', include('story_10.urls')),
    re_path(r'^login/$', views.LoginView.as_view(), name='login'),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    re_path(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    re_path(r'^$', index_lab1, name='index'),

]

story_9/urls.py
from django.urls import re_path
from .views import *
from django.contrib.auth import views
from django.conf.urls import include
#url for app

app_name = "story_9"
urlpatterns = [
    re_path(r'^books$', index, name='index'),
    re_path(r'^data/$', get_books, name='data'),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    re_path(r'^logout$', logout , name='logout'),
    re_path(r'^increasefav/', increasefav, name='increasefav'),
	re_path(r'^decreasefav/', decreasefav, name='decreasefav'),
]

story_9/models.py
from django.db import models

# Create your models here.

story_9/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.http import HttpResponseRedirect
import requests


# Create your views here.
def index(request):
	if request.user.is_authenticated:
		request.session['user'] = request.user.username
		request.session['email'] = request.user.email
		request.session.setdefault('counter',0)
	return render(request, 'bookz.html')

def get_books(request):
	search = request.GET.get('cari')
	url = "https://www.googleapis.com/books/v1/volumes?q=" + str(search)
	data = requests.get(url).json()
	return JsonResponse(data)

def logout(request):
	request.session.flush()
	return HttpResponseRedirect('./books')

def increasefav(request):
	request.session['counter'] = request.session['counter'] + 1
	return HttpResponse(request.session['counter'], content_type='application/json')

def decreasefav(request):
	request.session['counter'] = request.session['counter'] - 1
	return HttpResponse(request.session['counter'], content_type='application/json')

story_9/templates/bookz.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="{% static 'js/buku.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <title>books</title>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</head>
<body>
  <p class="title text-white" id="status" style="font-size: 50px; text-align: center"><strong>BOOKS</strong></p>
  <div class="row">
    <div class="search-box">
        <input class="search-txt" type="text" id="barbar" placeholder="type to search">
        <a class="search-btn" href="#" id="teken">
            <i class="fas fa-search"></i>
        </a>
    </div>

  {% if user.is_authenticated %}
    <header><a class="tulisan" href= "{% url 'story_9:logout'%}" style="text-transform:none; margin-top: 3%;">
      <div class="left">
        <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
      </div>
        Log Out
    </a>
    <p class="display-4 text-white">Hello, {{ user.username }}</p>
  </header>
  {% else %}
  <header><a class="tulisan" href="{% url 'social:begin' 'google-oauth2' %}" style="text-transform:none">
              <center><div class="left">
                  <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
              </div>
            Login with Google
          </a></center>
  </header>
  {% endif %}
  </div>
  <br>

  <div class = "container" >
    <div class = "text-right">
    <h2 id="statusBuku" class="text-white"><i class='fa fa-heart'style = 'color : #FF6F91'></i> {{ count }}</h2></div>
    <table class = "table table-striped" id = "shelf" style = "background-color: white"></table>
  </div>
</body>
</html>