lab_1/urls.py
from django.urls import re_path
from .views import *
#url for app

app_name = "lab_1"
urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^home/$', home, name='home'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^family/$', family, name='family'),
    re_path(r'^form/$', form, name='form'),
    re_path(r'^formz/$', form_sched, name='formz'),
    re_path(r'^formz/submit/$', create_sched, name='submit'),
    re_path(r'^formz/delete/$', delete_all, name='delete'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from django.contrib.auth import views
from lab_1.views import index as index_lab1


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls', namespace='lab_1')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^lab-8/', include('story_8.urls')),
    re_path(r'^lab-9/', include('story_9.urls')),
    re_path(r'^lab-10/', include('story_10.urls')),
    re_path(r'^login/$', views.LoginView.as_view(), name='login'),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    re_path(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    re_path(r'^$', index_lab1, name='index'),

]

templates/About.html
{% include 'Bars.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width" />
        <meta charset="UTF-8">
        <title>Introducing Me</title>
        <link rel= "stylesheet" type= "text/css" href= "{% static 'Style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body id="about">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1>GET TO KNOW ME BETTER</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4">

                </div>

                <div class="col-sm-4">
                    <center><a href="https://ibb.co/g1SeEe"><img src="https://preview.ibb.co/kG4Rue/IMG_8812.jpg" style="width:200px"/></a></center>
                </div>

                <div class="col-sm-4">
                    <h2 style="margin-top: 30%">MOTTO</h2>
                    <p>"wish for the best, prepare for the worst", wise man said.</p>
                    <h2>BORN IN</h2>
                    <p>Jakarta, September 14th 1999</p>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <p>Greetings! I'm Adinda. <br/>
                        Adinda Raisha Hanief Hawari is my full name. <br/>
                        My friends often call me by my last name, Hawari, and for short, Haw.
                    </p>
                </div>
            </div>
        </div>
    </body>
</html>

templates/Bars.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width" />
        <meta charset="UTF-8">
        <link rel= "stylesheet" type= "text/css" href= "{% static 'Style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="col-sm-6">
            <div>
                <a href="{% url 'lab_1:home' %}"><button class="button button1">HOME</button></a>
                <a href="{% url 'lab_1:about' %}"><button class="button button1">ABOUT</button></a>
                <a href="{% url 'lab_1:family' %}"><button class="button button1">FAMILY</button></a>
                <a href="{% url 'lab_1:form' %}"><button class="button button1">REGISTER</button></a>
                <a href="{% url 'lab_1:formz' %}"><button class="button button1">SCHEDULE</button></a>
            </div>
        </div>
    </body>
</html>

templates/Family.html
{% include 'Bars.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="UTF-8">
    <title>Family</title>
    <link rel= "stylesheet" type= "text/css" href= "{% static 'Style.css' %}">
</head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class="row" style="background-color: white;">
            <div class="col-sm-6">
                <h1>GET TO KNOW ME BETTER</h1>
            </div>
        </div>

        <div class="row" style="background-color: deeppink">

           <center> 
                <div class="col">
                    <a href="https://ibb.co/dGjmRe"><img src="https://preview.ibb.co/iX5FKz/40373c78_6512_455d_930d_c3ccd213563f.jpg" alt="40373c78_6512_455d_930d_c3ccd213563f" border="0"></a>
                    <a href="https://ibb.co/bZC6Re"><img src="https://preview.ibb.co/hqZaKz/HNF_8853.jpg" alt="HNF_8853" border="0"></a>
                    <a href="https://ibb.co/eZCZCK"><img src="https://preview.ibb.co/cjSO6e/IMG_4104.jpg" alt="IMG_4104" border="0"></a>
                    <a href="https://ibb.co/dvN1sK"><img src="https://preview.ibb.co/fiOVme/IMG_0790.jpg" alt="IMG_0790" border="0"></a>
                </div>
            </center>
        </div>
    </div>
</body>
</html>

templates/Form.html
{% include 'Bars.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="UTF-8">
    <title>Goodbye!</title>
    <link rel= "stylesheet" type= "text/css" href= "{% static 'Style.css' %}">
</head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
    <body class="format">
        <center>
            <div class="row">
                <div class="col-sm-6">
                    <br>
                    <h1>BE AN INSIDER</h1>
                </div>
            </div>

            <div class="col-sm-6">
                <br>
                <br>
            </div>
        </center>

            <div class="col-md-8">
                <form>
                    Name:<br>
                    <input type="text" name="name">
                    <br>
                    Date of Birth:<br>
                    <input type="date" name="date">
                    <br>
                    Email:<br>
                    <input type="email" name="imel">
                    <br>
                    Username:<br>
                    <input type="text" name="un">
                    <br>
                    Password:<br>
                    <input type="password" name="pw">
                    <br>
                    Password Confirmation:<br>
                    <input type="password" name="pwc">
                    <br>
                    <br>
                    <button id="tombol" class="button button1">DAFTAR</button>
                </form>
            </div>
    </body>
</html>

templates/Homepage.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Home</title>
        <link rel= "stylesheet" type= "text/css" href= "{% static 'Style.css' %}">
    </head>

    <body>
        <center>
            <div>
                <a href="{% url 'lab_1:home' %}"><button class="button button1">HOME</button></a>
            </div>

            <div>
                <a href="{% url 'lab_1:about' %}"><button class="button button1">ABOUT</button></a>
                <div class="divider"></div>
                <a href="{% url 'lab_1:family' %}"><button class="button button1">FAMILY</button></a>
            </div>

            <div>
                <a href="{% url 'lab_1:form' %}"><button class="button button1">REGISTER</button></a>
            </div>
        </center>

        <center><h1 class="greeting">CALL me HAW!</h1></center>
    </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/formz.html
{% include 'Bars.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="UTF-8">
    <title>Goodbye!</title>
    <link rel= "stylesheet" type= "text/css" href= "{% static 'Style.css' %}">
</head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
    <body class="format">
        <div class="container">
            <center>
                <div class="row">
                    <div class="col-sm-6">
                        <br>
                        <h1>BE AN INSIDER</h1>
                    </div>
                </div>

                <div class="col-sm-6">
                    <table class="bg-red" align= "center" border="2">
                        <th><center>Date</center></th>
                        <th><center>Activities</center></th>
                        <th><center>Place</center></th>
                        <th><center>Category</center></th>
                        {% for s in sched %}
                        <tr>
                            <td><center> {{ s.date }} </center></td>
                            <td><center> {{ s.activities }} </center></td>
                            <td><center> {{ s.place }} </center></td>
                            <td><center> {{ s.category }} </center></td>
                        </tr>
                        {% endfor %}
                    </table>
                    <br>
                    <br>
                </div>
            </center>


            <div class="col-md-6">
                <form action="{% url 'lab_1:submit' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <br>
                    <br>
                    <button id="tombol" class="button button1">DAFTAR</button>
                </form>
                <form action="{% url 'lab_1:delete' %}" method="post">
                    {% csrf_token %}
                    <button id="tombol" class="button button1">DELETE ALL</button>
                </form>
            </div>
        </div>
    </body>
</html>

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}